packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - authula@0.7.1
  - postcss@8.5.19
  - '@tanstack/form-core@1.33.2'
  - '@tanstack/react-form@1.33.2'
